apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
spec:
  selector:
    matchLabels:
      run: api-user
  replicas: 1
  template:
    metadata:
      labels:
        run: api-user
    spec:
      containers:
      - name: api-feed
        image: docker.io/beakalyk/udagram-api-user:v4a
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 200m
