apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    run: api-user

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user

  template:
    metadata:
      labels:
        app: api-user

    spec:
      containers:
      - name: api-user
        image: beakalyk/udagram-api-user:v3a
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "2024Mi"
            cpu: "500m"
        envFrom: 
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret   
        ports:
        - containerPort: 8080
      restartPolicy: Always